package local.corp.jira;
import com.intellij.ide.util.PropertiesComponent;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.options.*;
import javax.swing.*;import java.awt.*;import java.net.URI;
public final class JiraSettings implements Configurable {
 final Project project;JTextField jira,git,requiredText;JComboBox<String> language,statusMode;JCheckBox aiEnabled,gitRefresh,gitInfo,gitLogSync,gitProjectOnly;JLabel aiStatus;JButton syncGit;javax.swing.Timer remoteTimer;AccountSettings accountSettings;
 public JiraSettings(Project project){this.project=project;}
 static boolean aiEnabled(Project p){return PropertiesComponent.getInstance(p).getBoolean("corp.ai.enabled",true);}
 static String requiredText(Project p){return PropertiesComponent.getInstance(p).getValue("corp.jira.required.text","");}
 static int statusMode(Project p){return Math.max(0,Math.min(2,PropertiesComponent.getInstance(p).getInt("corp.jira.status.mode",2)));}
 static String jira(Project p){return PropertiesComponent.getInstance(p).getValue("corp.jira.host","");}
 static boolean gitProjectOnly(Project p){return PropertiesComponent.getInstance(p).getBoolean("corp.git.info.project.only",false);}
 static boolean gitInfo(Project p){return PropertiesComponent.getInstance(p).getBoolean("corp.git.info",false);}
 static boolean gitLogSync(Project p){return PropertiesComponent.getInstance(p).getBoolean("corp.git.log.sync",true);}
 static boolean gitRefresh(Project p){return PropertiesComponent.getInstance(p).getBoolean("corp.git.refresh",false);}
 static String git(Project p){return PropertiesComponent.getInstance(p).getValue("corp.git.host","");}
 static String normalize(String value,boolean optional){String s=value.trim();if(s.isEmpty()){if(optional)return "";throw new IllegalArgumentException(I18n.t("Укажите адрес Jira"));}if(!s.contains("://"))s="https://"+s;URI u=URI.create(s);if(!"https".equals(u.getScheme())||u.getHost()==null||u.getUserInfo()!=null||u.getQuery()!=null||u.getFragment()!=null)throw new IllegalArgumentException(I18n.t("Укажите HTTPS адрес без пароля, query и fragment"));if(optional&&u.getPath()!=null&&!u.getPath().matches("/?"))throw new IllegalArgumentException(I18n.t("GitLab: укажите только адрес сервера"));return s.replaceAll("/+$","");}
 public String getDisplayName(){return "Corp Jira - My task";}
 public JComponent createComponent(){
  disposeUIResources();JTabbedPane tabs=new JTabbedPane();JPanel basic=new JPanel(new GridLayout(0,1,6,6));jira=new JTextField();git=new JTextField();language=new JComboBox<>(new String[]{"EN","RU"});basic.add(new JLabel(I18n.t("Язык")));basic.add(language);basic.add(new JLabel(I18n.t("Изменение языка применяется после перезапуска WebStorm.")));basic.add(new JLabel(I18n.t("Адрес Jira (HTTPS, допускается context path)")));basic.add(jira);basic.add(new JLabel(I18n.t("После изменения адресов нажмите «Обновить» в панели Jira.")));JPanel basicPage=new JPanel(new BorderLayout());basicPage.add(basic,BorderLayout.NORTH);tabs.addTab(I18n.t("Основное"),basicPage);
  tabs.addTab("Git",createGitPage());
  JPanel agents=new JPanel();agents.setLayout(new BoxLayout(agents,BoxLayout.Y_AXIS));aiEnabled=new JCheckBox(I18n.t("Подключить задачи Jira к AI Assistant"));agents.add(aiEnabled);agents.add(Box.createVerticalStrut(8));agents.add(new JLabel(I18n.t("Интеграция: JetBrains AI Assistant → ChatGPT / Codex")));aiStatus=new JLabel();agents.add(Box.createVerticalStrut(8));agents.add(aiStatus);
  JPanel buttons=new JPanel(new FlowLayout(FlowLayout.LEFT,0,0));JButton connect=new JButton(I18n.t("Открыть AI Assistant")),check=new JButton(I18n.t("Проверить подключение"));buttons.add(connect);buttons.add(Box.createHorizontalStrut(8));buttons.add(check);buttons.setAlignmentX(Component.LEFT_ALIGNMENT);agents.add(Box.createVerticalStrut(10));agents.add(buttons);
  JTextArea help=new JTextArea(I18n.t("Как подключить\n\n1. Settings → Plugins: установите и включите JetBrains AI Assistant.\n2. Откройте AI Chat в WebStorm.\n3. Выберите Codex в списке агентов и выполните вход через ChatGPT\n   или настройте поддерживаемый способ авторизации в AI Assistant.\n4. Нажмите «Проверить подключение», затем «Применить».\n\nАгент и модель нового чата выбираются в AI Assistant.\nТокены AI вводятся только в AI Assistant — здесь они не хранятся.\nКнопка в задаче появляется только при подтверждённом подключении.\nЗадача и медиа вставляются в новый чат как черновик."));help.setEditable(false);help.setOpaque(false);help.setLineWrap(true);help.setWrapStyleWord(true);help.setFont(UIManager.getFont("Label.font"));help.setAlignmentX(Component.LEFT_ALIGNMENT);help.setBorder(BorderFactory.createEmptyBorder(16,0,0,0));agents.add(help);JPanel agentsPage=new JPanel(new BorderLayout());agentsPage.add(agents,BorderLayout.NORTH);tabs.addTab(I18n.t("Агенты"),agentsPage);
  JPanel task=new JPanel();task.setLayout(new BoxLayout(task,BoxLayout.Y_AXIS));task.setBorder(BorderFactory.createEmptyBorder(12,12,12,12));JLabel statusTitle=new JLabel(I18n.t("Статус"));statusTitle.setAlignmentX(Component.LEFT_ALIGNMENT);task.add(statusTitle);task.add(Box.createVerticalStrut(6));JPanel statusRow=new JPanel(new FlowLayout(FlowLayout.LEFT,0,0));statusRow.setAlignmentX(Component.LEFT_ALIGNMENT);statusRow.add(new JLabel(I18n.t("Показывать")));statusRow.add(Box.createHorizontalStrut(10));statusMode=new JComboBox<>(new String[]{I18n.t("Все"),I18n.t("Доступные"),I18n.t("Обычный")});statusRow.add(statusMode);task.add(statusRow);task.add(Box.createVerticalStrut(3));String[] statusHints={I18n.t("Все — все статусы из каталога Jira."),I18n.t("Доступные — статусы с известным прямым или многошаговым маршрутом."),I18n.t("Обычный — только переходы, доступные сейчас в Jira.")};JLabel statusHint=new JLabel(statusHints[0]);statusHint.setAlignmentX(Component.LEFT_ALIGNMENT);statusHint.setForeground(com.intellij.util.ui.UIUtil.getLabelDisabledForeground());statusMode.addActionListener(e->{int index=statusMode.getSelectedIndex();if(index>=0)statusHint.setText(statusHints[index]);});task.add(statusHint);JPanel requiredBlock=new JPanel();requiredBlock.setOpaque(false);requiredBlock.setLayout(new BoxLayout(requiredBlock,BoxLayout.Y_AXIS));requiredBlock.setAlignmentX(Component.LEFT_ALIGNMENT);requiredBlock.add(Box.createVerticalStrut(16));JLabel requiredLabel=new JLabel(I18n.t("Заполнение обязательных полей"));requiredLabel.setAlignmentX(Component.LEFT_ALIGNMENT);requiredBlock.add(requiredLabel);requiredBlock.add(Box.createVerticalStrut(6));requiredText=new JTextField(32);requiredText.setAlignmentX(Component.LEFT_ALIGNMENT);requiredBlock.add(requiredText);requiredBlock.add(Box.createVerticalStrut(3));JLabel requiredHint=new JLabel(I18n.t("Текст для обязательных текстовых полей при переходах по маршруту (красные статусы)."));requiredHint.setForeground(com.intellij.util.ui.UIUtil.getLabelDisabledForeground());requiredHint.setAlignmentX(Component.LEFT_ALIGNMENT);requiredBlock.add(requiredHint);task.add(requiredBlock);statusMode.addActionListener(e->{requiredBlock.setVisible(statusMode.getSelectedIndex()!=2);task.revalidate();task.repaint();});requiredBlock.setVisible(statusMode.getSelectedIndex()!=2);JPanel taskPage=new JPanel(new BorderLayout());taskPage.add(task,BorderLayout.NORTH);tabs.addTab(I18n.t("Задача"),taskPage);
  JPanel about=new JPanel();about.setLayout(new BoxLayout(about,BoxLayout.Y_AXIS));about.setBorder(BorderFactory.createEmptyBorder(12,12,12,12));about.add(new JLabel("Corp Jira - My task"));about.add(Box.createVerticalStrut(8));var descriptor=com.intellij.ide.plugins.PluginManagerCore.getPlugin(com.intellij.openapi.extensions.PluginId.getId("local.corp.jira.myTasks"));about.add(new JLabel(I18n.t("Версия: ")+(descriptor==null?I18n.t("не определена"):descriptor.getVersion())));about.add(Box.createVerticalStrut(16));JButton github=new JButton("GitHub");JiraToolWindowFactory.iconButton(github,"https://github.com/denis-hik/corp-jira-my-task-public");github.setForeground(com.intellij.ui.JBColor.BLUE);github.addActionListener(e->com.intellij.ide.BrowserUtil.browse("https://github.com/denis-hik/corp-jira-my-task-public"));about.add(github);for(Component component:about.getComponents())if(component instanceof JComponent c)c.setAlignmentX(Component.LEFT_ALIGNMENT);JPanel aboutPage=new JPanel(new BorderLayout());aboutPage.add(about,BorderLayout.NORTH);tabs.addTab(I18n.t("Об аддоне"),aboutPage);accountSettings=new AccountSettings(project,tabs);
  connect.addActionListener(e->{var window=com.intellij.openapi.wm.ToolWindowManager.getInstance(project).getToolWindow("AIAssistant");if(window!=null){window.activate(null);aiStatus.setText(I18n.t("AI Assistant открыт. Выполните вход и проверьте подключение."));}else aiStatus.setText(I18n.t("Откройте AI Chat через View → Tool Windows; если его нет — включите плагин."));});check.addActionListener(e->checkConnection());aiEnabled.addActionListener(e->checkConnection());reset();refreshRemotes();remoteTimer=new javax.swing.Timer(2000,e->refreshRemotes());remoteTimer.start();return tabs;
 }
 JComponent createGitPage(){
  JPanel form=new JPanel(new GridBagLayout());form.setBorder(com.intellij.util.ui.JBUI.Borders.empty(16));
  gitHeading(form,0,"Git Info (Jira Development)",0);
  gitInfo=new JCheckBox(I18n.t("Показывать панель в задаче"));gitRow(form,gitInfo,1,0,8);
  gitRow(form,gitHint("Коммиты, ветки и pull requests из Jira Development."),2,24,2);
  gitProjectOnly=new JCheckBox(I18n.t("Только репозитории текущего проекта"));gitRow(form,gitProjectOnly,3,24,8);
  gitRow(form,gitHint("Фильтр по Git remotes проекта WebStorm."),4,48,2);
  gitInfo.addItemListener(e->gitProjectOnly.setEnabled(gitInfo.isSelected()));

  gitHeading(form,5,"Git Log WebStorm",22);
  gitLogSync=new JCheckBox(I18n.t("Переходить к локальным коммитам"));gitRow(form,gitLogSync,6,0,8);
  gitRow(form,gitHint("Показывает иконку Git Log рядом с найденными коммитами."),7,24,2);
  JLabel hostLabel=new JLabel(I18n.t("GitLab для ссылок в комментариях"));hostLabel.setLabelFor(git);gitRow(form,hostLabel,8,24,12);
  JPanel hostRow=new JPanel(new BorderLayout(com.intellij.util.ui.JBUI.scale(8),0));hostRow.add(git);
  syncGit=new JButton(I18n.t("Из проекта"));syncGit.setVisible(false);syncGit.setToolTipText(I18n.t("Подставить адрес сервера из Git remote проекта"));syncGit.addActionListener(e->syncFromGit());hostRow.add(syncGit,BorderLayout.EAST);gitRow(form,hostRow,9,24,4);
  gitRow(form,gitHint("Необязательно. Пустое поле отключает поиск по ссылкам в комментариях."),10,24,3);

  gitHeading(form,11,I18n.t("Обновление задачи"),22);
  gitRefresh=new JCheckBox(I18n.t("Обновлять после операций Git"));gitRow(form,gitRefresh,12,0,8);
  gitRow(form,gitHint("Перечитывает открытую задачу после push, pull и обновления проекта."),13,24,2);
  JPanel page=new JPanel(new BorderLayout());page.add(form,BorderLayout.NORTH);
  var scroll=new com.intellij.ui.components.JBScrollPane(page);scroll.setBorder(BorderFactory.createEmptyBorder());scroll.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);return scroll;
 }
 static void gitRow(JPanel panel,JComponent component,int row,int indent,int top){
  GridBagConstraints c=new GridBagConstraints();c.gridx=0;c.gridy=row;c.weightx=1;c.fill=GridBagConstraints.HORIZONTAL;c.anchor=GridBagConstraints.NORTHWEST;c.insets=com.intellij.util.ui.JBUI.insets(top,indent,0,0);panel.add(component,c);
 }
 static void gitHeading(JPanel panel,int row,String title,int top){
  JPanel heading=new JPanel(new BorderLayout(com.intellij.util.ui.JBUI.scale(10),0));JLabel label=new JLabel(title);label.setFont(label.getFont().deriveFont(Font.BOLD));heading.add(label,BorderLayout.WEST);JPanel line=new JPanel(new GridBagLayout());GridBagConstraints c=new GridBagConstraints();c.weightx=1;c.fill=GridBagConstraints.HORIZONTAL;line.add(new JSeparator(),c);heading.add(line);gitRow(panel,heading,row,0,top);
 }
 static JTextArea gitHint(String key){
  JTextArea hint=new JTextArea(I18n.t(key),1,36);hint.setEditable(false);hint.setFocusable(false);hint.setOpaque(false);hint.setLineWrap(true);hint.setWrapStyleWord(true);hint.setFont(com.intellij.util.ui.UIUtil.getLabelFont().deriveFont(com.intellij.util.ui.UIUtil.getLabelFont().getSize2D()-1));hint.setForeground(com.intellij.util.ui.UIUtil.getLabelDisabledForeground());hint.setBorder(BorderFactory.createEmptyBorder());return hint;
 }
 static String remoteHost(String remote){try{String s=remote.trim();if(s.matches("^[^/]+@[^:]+:.*"))s="ssh://"+s.replaceFirst(":","/");URI u=URI.create(s);String scheme=u.getScheme();if(scheme==null||!java.util.Set.of("https","http","ssh","git").contains(scheme)||u.getHost()==null)return "";int port=(scheme.equals("https")||scheme.equals("http"))?u.getPort():-1;return new URI("https",null,u.getHost(),port,null,null,null).toString();}catch(Exception ignored){return "";}}
 java.util.List<String> remoteHosts(){java.util.Set<String> hosts=new java.util.TreeSet<>();if(!project.isDisposed())for(var repo:git4idea.GitUtil.getRepositories(project))for(var remote:repo.getRemotes())for(String url:remote.getUrls()){String host=remoteHost(url);if(!host.isEmpty())hosts.add(host);}return new java.util.ArrayList<>(hosts);}
 void refreshRemotes(){if(syncGit!=null)syncGit.setVisible(!remoteHosts().isEmpty());}
 void syncFromGit(){var hosts=remoteHosts();if(hosts.isEmpty()){syncGit.setVisible(false);return;}if(hosts.size()==1){git.setText(hosts.get(0));return;}com.intellij.openapi.ui.popup.JBPopupFactory.getInstance().createPopupChooserBuilder(hosts).setTitle(I18n.t("Выберите Git-сервер")).setItemChosenCallback(host->git.setText(host)).createPopup().showUnderneathOf(syncGit);}
 @Override public void disposeUIResources(){if(accountSettings!=null){accountSettings.close();accountSettings=null;}if(remoteTimer!=null){remoteTimer.stop();remoteTimer=null;}requiredText=null;jira=null;git=null;language=null;statusMode=null;aiEnabled=null;gitRefresh=null;gitInfo=null;gitLogSync=null;gitProjectOnly=null;aiStatus=null;syncGit=null;}
 void checkConnection(){aiStatus.setText(!aiEnabled.isSelected()?I18n.t("Интеграция выключена; кнопка в задаче скрыта."):AiChatBridge.connectionStatus(project));}
 public boolean isModified(){return gitProjectOnly.isSelected()!=gitProjectOnly(project)||gitInfo.isSelected()!=gitInfo(project)||gitLogSync.isSelected()!=gitLogSync(project)||gitRefresh.isSelected()!=gitRefresh(project)||!requiredText.getText().trim().equals(requiredText(project))||statusMode.getSelectedIndex()!=statusMode(project)||!java.util.Objects.equals(language.getSelectedItem(),I18n.preference())||aiEnabled.isSelected()!=aiEnabled(project)||!jira.getText().trim().equals(jira(project))||!git.getText().trim().equals(git(project));}
 public void reset(){gitProjectOnly.setSelected(gitProjectOnly(project));gitInfo.setSelected(gitInfo(project));gitProjectOnly.setEnabled(gitInfo.isSelected());gitLogSync.setSelected(gitLogSync(project));gitRefresh.setSelected(gitRefresh(project));requiredText.setText(requiredText(project));statusMode.setSelectedIndex(statusMode(project));language.setSelectedItem(I18n.preference());jira.setText(jira(project));git.setText(git(project));aiEnabled.setSelected(aiEnabled(project));checkConnection();}
 public void apply()throws ConfigurationException{try{if(statusMode.getSelectedIndex()!=2&&requiredText.getText().isBlank())throw new IllegalArgumentException(I18n.t("Укажите текст для обязательных полей."));String j=jira.getText().isBlank()?"":normalize(jira.getText(),false),g=normalize(git.getText(),true);PropertiesComponent.getInstance(project).setValue("corp.jira.required.text",requiredText.getText().trim());PropertiesComponent.getInstance(project).setValue("corp.jira.status.mode",Integer.toString(statusMode.getSelectedIndex()));PropertiesComponent.getInstance().setValue(I18n.KEY,(String)language.getSelectedItem());PropertiesComponent.getInstance(project).setValue("corp.jira.host",j);PropertiesComponent.getInstance(project).setValue("corp.git.host",g);PropertiesComponent.getInstance(project).setValue("corp.git.info.project.only",gitProjectOnly.isSelected(),false);PropertiesComponent.getInstance(project).setValue("corp.git.info",gitInfo.isSelected(),false);PropertiesComponent.getInstance(project).setValue("corp.git.log.sync",gitLogSync.isSelected(),true);PropertiesComponent.getInstance(project).setValue("corp.git.refresh",gitRefresh.isSelected(),false);PropertiesComponent.getInstance(project).setValue("corp.ai.enabled",aiEnabled.isSelected(),true);}catch(Exception e){throw new ConfigurationException(e.getMessage());}}
}
